# Generated by Django 3.0.6 on 2020-05-12 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'routine',
            },
        ),
        migrations.CreateModel(
            name='RoutineInstruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('video_link', models.CharField(blank=True, max_length=128, null=True, verbose_name='link')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine.Routine', verbose_name='routine')),
            ],
            options={
                'verbose_name': 'routine video',
            },
        ),
    ]
