# Generated by Django 3.0.6 on 2020-05-13 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routineinstruction',
            options={'verbose_name': 'routine instruction'},
        ),
    ]
