# Generated by Django 3.0.6 on 2020-05-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0003_routine_training_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='routineinstruction',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='order'),
        ),
    ]
