# Generated by Django 3.0.6 on 2020-05-27 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0005_auto_20200526_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='effort_level',
            field=models.CharField(blank=True, choices=[('LW', 'Bajo'), ('MD', 'Medio'), ('HI', 'Alto')], default='LW', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='routine',
            name='estimated_duration',
            field=models.DurationField(blank=True, null=True, verbose_name='estimated duration'),
        ),
    ]
