# Generated by Django 3.0.6 on 2020-05-28 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0006_auto_20200527_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='order'),
        ),
    ]
