# Generated by Django 3.0.6 on 2020-05-26 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20200524_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traininggroup',
            options={'verbose_name': 'training group'},
        ),
    ]
