# Generated by Django 3.0.6 on 2020-05-26 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20200524_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='training_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.TrainingGroup', verbose_name='training group'),
        ),
    ]
